version: "3.9"

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: doc-management-frontend
    ports:
      - "3000:3000"
    env_file:
      - .env.local
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev -- -H 0.0.0.0 -p 3000
